export const SPORTS_ASSETS = {
    states: [
        { name: 'Malaysia (National)', url: 'https://upload.wikimedia.org/wikipedia/commons/6/66/Flag_of_Malaysia.svg' },
        { name: 'Selangor', url: 'https://upload.wikimedia.org/wikipedia/commons/0/09/Flag_of_Selangor.svg' },
        { name: 'Johor', url: 'https://upload.wikimedia.org/wikipedia/commons/5/5a/Flag_of_Johor.svg' },
        { name: 'Penang', url: 'https://upload.wikimedia.org/wikipedia/commons/d/d4/Flag_of_Penang_%28Malaysia%29.svg' },
        { name: 'Perak', url: 'https://upload.wikimedia.org/wikipedia/commons/8/87/Flag_of_Perak.svg' },
        { name: 'Kedah', url: 'https://upload.wikimedia.org/wikipedia/commons/c/cc/Flag_of_Kedah.svg' },
        { name: 'Kelantan', url: 'https://upload.wikimedia.org/wikipedia/commons/6/61/Flag_of_Kelantan.svg' },
        { name: 'Terengganu', url: 'https://upload.wikimedia.org/wikipedia/commons/6/6c/Flag_of_Terengganu.svg' },
        { name: 'Pahang', url: 'https://upload.wikimedia.org/wikipedia/commons/a/aa/Flag_of_Pahang.svg' },
        { name: 'Negeri Sembilan', url: 'https://upload.wikimedia.org/wikipedia/commons/d/db/Flag_of_Negeri_Sembilan.svg' },
        { name: 'Melaka', url: 'https://upload.wikimedia.org/wikipedia/commons/0/09/Flag_of_Malacca.svg' },
        { name: 'Perlis', url: 'https://upload.wikimedia.org/wikipedia/commons/a/aa/Flag_of_Perlis.svg' },
        { name: 'Sabah', url: 'https://upload.wikimedia.org/wikipedia/commons/b/b5/Flag_of_Sabah.svg' },
        { name: 'Sarawak', url: 'https://upload.wikimedia.org/wikipedia/commons/7/7e/Flag_of_Sarawak.svg' },
        { name: 'WP Kuala Lumpur', url: 'https://upload.wikimedia.org/wikipedia/commons/6/64/Flag_of_Kuala_Lumpur_%28Malaysia%29.svg' },
    ],
    football_clubs: [
        { name: 'JDT FC', url: 'https://upload.wikimedia.org/wikipedia/en/e/ee/Johor_Darul_Takzim_FC_logo.svg' },
        { name: 'Selangor FC', url: 'https://upload.wikimedia.org/wikipedia/en/8/87/Selangor_FC_logo.svg' },
        { name: 'Terengganu FC', url: 'https://upload.wikimedia.org/wikipedia/en/3/33/Terengganu_Football_Club_crest.svg' },
        { name: 'Kedah Darul Aman', url: 'https://upload.wikimedia.org/wikipedia/en/thumb/0/0a/Kedah_Darul_Aman_FC_logo.svg/1200px-Kedah_Darul_Aman_FC_logo.svg.png' },
        { name: 'Sabah FC', url: 'https://upload.wikimedia.org/wikipedia/en/2/26/Sabah_FA_Logo.svg' },
        { name: 'KL City FC', url: 'https://upload.wikimedia.org/wikipedia/en/1/1f/Kuala_Lumpur_City_FC_logo.svg' },
        { name: 'Perak FC', url: 'https://upload.wikimedia.org/wikipedia/en/a/ad/Perak_FC_logo.svg' },
        { name: 'Sri Pahang FC', url: 'https://upload.wikimedia.org/wikipedia/en/0/08/Sri_Pahang_FC_logo.svg' },
    ],
    countries: [
        { name: 'China', url: 'https://upload.wikimedia.org/wikipedia/commons/f/fa/Flag_of_the_People%27s_Republic_of_China.svg' },
        { name: 'Indonesia', url: 'https://upload.wikimedia.org/wikipedia/commons/9/9f/Flag_of_Indonesia.svg' },
        { name: 'Japan', url: 'https://upload.wikimedia.org/wikipedia/en/9/9e/Flag_of_Japan.svg' },
        { name: 'Korea', url: 'https://upload.wikimedia.org/wikipedia/commons/0/09/Flag_of_South_Korea.svg' },
        { name: 'Denmark', url: 'https://upload.wikimedia.org/wikipedia/commons/9/9c/Flag_of_Denmark.svg' },
        { name: 'Thailand', url: 'https://upload.wikimedia.org/wikipedia/commons/a/a9/Flag_of_Thailand.svg' },
        { name: 'Singapore', url: 'https://upload.wikimedia.org/wikipedia/commons/4/48/Flag_of_Singapore.svg' },
        { name: 'India', url: 'https://upload.wikimedia.org/wikipedia/en/4/41/Flag_of_India.svg' },
    ]
};
